### ISSUE TITLE
missing line && form action

### ISSUE THREAD

**Issue by sanasol** [carloquilala/fluxbb#1]
1:
https://github.com/jupeto/fluxbb/blob/master/diff-files/fluxcp-for-fluxbb-diff.patch#L207
this line missing in "howto"
http://artworx.juplo.com/?module=fluxbb&action=howto

2:
also after install form forum cant generate config coz of form action is "?module=fluxbb&action=install.php" instead of "?module=fluxbb&action=install"

**Comment by sanasol** [comment]
3:
aaand https://github.com/jupeto/fluxbb/blob/master/themes/default/fluxbb/footer.php#L156

exit really? what if i have footer modules/counters and other :)

**Comment by carloquilala** [comment]
the application wasn't designed to have footer modules in the first place :D
 

On Thursday, October 17, 2013 5:02 PM, Alex notifications@github.com wrote:

3:
aaand https://github.com/jupeto/fluxbb/blob/master/themes/default/fluxbb/footer.php#L156
exit really? what if i have footer modules/counters and other :)
